function [out] = PhasedSetup(scenario)
%PHASEDSETUP Sets up Phased Array Toolbox system objects for SEMTA
%   Takes scenario.wave and scenario.traj as input and outputs
%   scenario.phased struct containing system objects for Phased Array
%   Toolbox simulation.

%% Unpack Variables

radarsetup = scenario.radarsetup;
traj = scenario.traj;
multi = scenario.multi;

%% Set up constants

c = physconst('LightSpeed');
lambda = c/radarsetup.f_c;

%% Signal Setup

% Transmit waveform
out.waveform = phased.LinearFMWaveform( ...
    'SampleRate',               radarsetup.f_s, ...
    'DurationSpecification',    'Pulse width', ...
    'PulseWidth',               radarsetup.t_p, ...
    'PRF',                      radarsetup.prf, ...
    'SweepBandwidth',           radarsetup.bw, ...
    'SweepDirection',           'Up', ...
    'SweepInterval',            'Positive', ...
    'OutputFormat',             'Pulses', ...
    'NumPulses',                1);

%% Target & Channel Setup

%TODO: CORRECT TRAJECTORY
% Model target position and motion
out.target_plat = phased.Platform( ...
    ...
    'MotionModel',              'Custom', ...
    'CustomTrajectory',         traj.full_traj);

% Set up target to take RCS value at each object call
out.target = phased.RadarTarget( ...
    ...
    'EnablePolarization',       false, ...
    'MeanRCSSource',            'Input port', ...
    'Model',                    'Nonfluctuating', ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'PropagationSpeed',         c);

% Set up two-way free space path loss
out.target_chan = phased.FreeSpace( ...
    ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'TwoWayPropagation',        true, ...
    'SampleRate',               radarsetup.f_s);

%% Transceiver Setup

% Transceiver position and motion
out.radar_plat = phased.Platform( ...
    ...
    'MotionModel',              'Velocity', ...
    'InitialPosition',          multi.radar_pos(:,1), ...
    'Velocity',                 [0;0;0]);

% Set up antenna array parameters
out.antenna = phased.CosineAntennaElement( ...
    ...
    'FrequencyRange',           radarsetup.f_c*[0.9 1.1], ...
    'CosinePower',              [1.5 186]);

if radarsetup.n_ant == 1
    out.array = out.antenna;
else
    out.sub_array = phased.ULA( ...
        ...
        'Element',                  out.antenna, ...
        'NumElements',              radarsetup.n_ant, ...
        'ArrayAxis',                'y', ...
        'ElementSpacing',           lambda/2);
    
    out.array = phased.ReplicatedSubarray( ...
        ...
        'Subarray',                 out.sub_array, ...
        'Layout',                   'Custom', ...
        'SubarrayPosition',         [0 0; 0 0; 0 0], ...
        'SubarrayNormal',           [0 0; 0 0]);
end

% Set up transmitter parameters
out.transmitter = phased.Transmitter( ...
    'PeakPower',                radarsetup.tx_pow, ...
    'Gain',                     0, ...
    'InUseOutputPort',          true);

out.radiator = phased.Radiator( ...
    'Sensor',                   out.sub_array, ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'CombineRadiatedSignals',   true);

% Set up receiver parameters
out.collector = phased.Collector( ...
    'Sensor',                   out.array, ...
    'PropagationSpeed',         c, ...
    'OperatingFrequency',       radarsetup.f_c, ...
    'Wavefront',                'Plane');

out.receiver = phased.ReceiverPreamp( ...
    'Gain',                     radarsetup.rx_sys_gain, ...
    'NoiseFigure',              radarsetup.rx_nf, ...
    'SampleRate',               radarsetup.f_s, ...
    'EnableInputPort',          true);


end

