%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.8 and Fixed-Point Designer 7.0           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function y = DopplerProcessingFP_fixpt(x)
%DOPPLERPROCESSINGFP Fixed point Doppler processing
%   Takes range-processed signal as input, returns FFT

%% Set up FFT object

% Instantiate FFT object
fm = get_fimath();

ft = dsp.FFT( ...
    'FFTImplementation',        'Radix-2', ...
    'BitReversedOutput',        false, ...
    'Normalize',                false, ...
    'FFTLengthSource',          'Property', ...
    'FFTLength',                1024, ...
    'WrapInput',                true);

%% Perform Doppler FFT

% Take FFT of input signal
X_f = fi(ft(x), 1, 32, 25, fm);

% FFT shift signal
y = fi(fftshift(X_f), 1, 32, 25, fm);

end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
